### ISSUE TITLE
Performance test insights QPC report processing (10K System QPC report)

### ISSUE THREAD

**Issue by kholdaway** [quipucords/yupana#59]
Both RHSM and QPC will be uploading large datasets into the host inventory service. Currently, the host inventory has no bulk API. This issue is a simple test to see how well file upload service, yupana, and host inventory service perform with a 10K QPC System report.

Document how long it takes yupana to process a 10K system report.  Interesting data points:
- How long validation takes
- How long uploading to host inventory service takes

**Comment by abaiken** [comment]
The results of the performance tests were as follows: 

1. 20 systems: Validation = `.03` seconds, Host Inventory Upload = `.33` seconds
2. 7k systems: Validation = `.30` seconds, Host Inventory Upload =`141.1` seconds
3. 20k systems: Validation = `0.27` seconds, Host Inventory Upload = `530.3` seconds

During the above tests, I found that I needed to increase the session timeout for the consumer, but it was capped at 300 seconds (because that is the default for the broker's `group_max_session_timeout_ms` and the session timeout must be below this). This was adequate for the 7k system but not the 20k system - so you get kicked off of the qpc-group and have to rejoin.
